export { default as Home } from './Home'
export { default as Review } from './Review'
export { default as TableBooking } from './TableBooking'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Admin } from './Admin'