version: '3.8'
services:
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ajakolis
      MONGO_INITDB_ROOT_PASSWORD: TestPassword
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data
volumes:
  mongodata:
    driver: local